In [5]:
import numpy as np
np.__version__

'1.16.4'

In [6]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
import numpy as np
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [49]:
import numpy as np
a=np.arange(9).reshape(3,3)
b=np.ndim(a)
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [89]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9],dtype=int)    # declare dtype in initializing numpy array
b=arr[arr%2==1]
b

array([1, 3, 5, 7, 9])

In [93]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9],dtype=int)    # declare dtype in initializing numpy array
arr[arr%2==1]=-1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [105]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
b2=np.where(arr%2==1,-1,arr)   # -1 is the broadcaster
print(b2)
print(arr)
np.where?

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [111]:
import numpy as np
arr2=np.arange(10)
arr2.reshape(2,-1)   # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])