# Numpy

## To check the numpy version in the system

In [1]:
import numpy as np
np.__version__

'1.15.1'

###  Single Dimensional Array

In [6]:
import numpy as np
a=[1,56,89]
np.array(a)

array([ 1, 56, 89])

### Two Dimensional Array(This is generally used)

In [15]:
import numpy as np
b=[5,4,3], [1,2,3]
np.array(b)


array([[5, 4, 3],
       [1, 2, 3]])

In [7]:
import numpy as np
b=[5,4,3], [1,2,3]
b1=np.array(b)            #---> np.array is used to convert python list to array
print(b1)                 #---> print b1 values
print(b1+10)              #--->You could perform mathematical operations like additions, subtraction, division and multiplication on an array. The syntax is the array name followed by the operation (+.-,*,/) followed by the operand 

[[5 4 3]
 [1 2 3]]
[[15 14 13]
 [11 12 13]]


# Shape of an Array

### You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes 

In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)  #---------> specifies the shape of the array id it is 2x2 or 3x3 or 1x1 matrcix
print(a.size)   #----------> count of the each element present in the array
print(a.dtype)

(2, 3)
6
int32


## Three Dimensional Array

In [1]:
import numpy as np
a1=np.array([[[1,2,3],[2,4,5]]])
print(a1.shape)

(1, 2, 3)


# numpy.zeros() and numpy.ones() in Python 


What is np.zeros and np.ones?
You can create a matrix full of zeroes or ones using np.zeros and np.one commands respectively. It can be used when you initialized the weights during the first iteration in TensorFlow and other statistic tasks. 

# # The syntax is 
### Numpy Zero 
numpy.zeros(shape, dtype=float, order='C')
### Numpy Once 
numpy.ones(shape, dtype=float, order='C')

#### Here, 
Shape: is the shape of the array 
Dtype: is the datatype. It is optional. The default value is float64
Order: Default is C which is an essential row style. 

#### To print 2x2 matrix with Zeros and ones

In [22]:
import numpy as np
a2=np.array([[1,4,5],[3,6,7]])
print(a2)
np.zeros((2,2),dtype=int,order='C')

[[1 4 5]
 [3 6 7]]


array([[0, 0],
       [0, 0]])

#### To print 2x2 matrix with ones and with datatype in output, type np.dtype=int16

In [30]:
import numpy as np
np.ones([2,2], dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

#### To Reshape a given numpy variable. you can reshape only if the size are same. 

In [33]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.reshape(3,2)

[[2 4 5]
 [5 9 4]]


array([[2, 4],
       [5, 5],
       [9, 4]])

#### If we try to give the reshape value as 3,5 which should have 15 elements in array it displays an error. it should only have the size of the array so that we can reshape

In [34]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.reshape(3,5)

[[2 4 5]
 [5 9 4]]


ValueError: cannot reshape array of size 6 into shape (3,5)

# Flatten()

## When you deal with some neural network like convnet, you need to flatten the array. You can use flatten(). The syntax is 

### numpy.flatten(Order='C')

In [35]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.flatten()

[[2 4 5]
 [5 9 4]]


array([2, 4, 5, 5, 9, 4])